import 'package:flutter/widgets.dart';

/// Tx Browser Curated High-Performance Icon Set.
/// Uses single static Lucide icon font with full compiler tree-shaking support.
class LucideIcons {
  const LucideIcons._();

  static const IconData activity = IconData(57400, fontFamily: 'Lucide');
  static const IconData alertCircle = IconData(57463, fontFamily: 'Lucide');
  static const IconData arrowDownToLine = IconData(58453, fontFamily: 'Lucide');
  static const IconData arrowLeft = IconData(57416, fontFamily: 'Lucide');
  static const IconData arrowRight = IconData(57417, fontFamily: 'Lucide');
  static const IconData arrowUpLeft = IconData(57419, fontFamily: 'Lucide');
  static const IconData ban = IconData(57425, fontFamily: 'Lucide');
  static const IconData bell = IconData(57433, fontFamily: 'Lucide');
  static const IconData bookOpen = IconData(57439, fontFamily: 'Lucide');
  static const IconData bookmark = IconData(57440, fontFamily: 'Lucide');
  static const IconData bookmarkCheck = IconData(58655, fontFamily: 'Lucide');
  static const IconData box = IconData(57441, fontFamily: 'Lucide');
  static const IconData camera = IconData(57444, fontFamily: 'Lucide');
  static const IconData cameraOff = IconData(57445, fontFamily: 'Lucide');
  static const IconData check = IconData(57452, fontFamily: 'Lucide');
  static const IconData checkCircle = IconData(57468, fontFamily: 'Lucide');
  static const IconData chevronDown = IconData(57453, fontFamily: 'Lucide');
  static const IconData chevronLeft = IconData(57454, fontFamily: 'Lucide');
  static const IconData chevronRight = IconData(57455, fontFamily: 'Lucide');
  static const IconData chevronUp = IconData(57456, fontFamily: 'Lucide');
  static const IconData clipboard = IconData(57477, fontFamily: 'Lucide');
  static const IconData clipboardCopy = IconData(57893, fontFamily: 'Lucide');
  static const IconData code = IconData(57491, fontFamily: 'Lucide');
  static const IconData copy = IconData(57502, fontFamily: 'Lucide');
  static const IconData delete = IconData(57518, fontFamily: 'Lucide');
  static const IconData download = IconData(57522, fontFamily: 'Lucide');
  static const IconData edit3 = IconData(57648, fontFamily: 'Lucide');
  static const IconData ellipsisVertical = IconData(57527, fontFamily: 'Lucide');
  static const IconData externalLink = IconData(57529, fontFamily: 'Lucide');
  static const IconData file = IconData(57536, fontFamily: 'Lucide');
  static const IconData filePenLine = IconData(58144, fontFamily: 'Lucide');
  static const IconData fileText = IconData(57548, fontFamily: 'Lucide');
  static const IconData film = IconData(57552, fontFamily: 'Lucide');
  static const IconData fingerprint = IconData(58059, fontFamily: 'Lucide');
  static const IconData folder = IconData(57559, fontFamily: 'Lucide');
  static const IconData folderArchive = IconData(58157, fontFamily: 'Lucide');
  static const IconData folderInput = IconData(58164, fontFamily: 'Lucide');
  static const IconData folderPlus = IconData(57561, fontFamily: 'Lucide');
  static const IconData folderX = IconData(58174, fontFamily: 'Lucide');
  static const IconData globe = IconData(57576, fontFamily: 'Lucide');
  static const IconData gripVertical = IconData(57579, fontFamily: 'Lucide');
  static const IconData hardDrive = IconData(57581, fontFamily: 'Lucide');
  static const IconData heartHandshake = IconData(58071, fontFamily: 'Lucide');
  static const IconData helpCircle = IconData(57474, fontFamily: 'Lucide');
  static const IconData history = IconData(57845, fontFamily: 'Lucide');
  static const IconData home = IconData(57589, fontFamily: 'Lucide');
  static const IconData image = IconData(57590, fontFamily: 'Lucide');
  static const IconData info = IconData(57593, fontFamily: 'Lucide');
  static const IconData keyRound = IconData(58531, fontFamily: 'Lucide');
  static const IconData keyboard = IconData(57988, fontFamily: 'Lucide');
  static const IconData layers = IconData(58665, fontFamily: 'Lucide');
  static const IconData layers2 = IconData(58666, fontFamily: 'Lucide');
  static const IconData layoutGrid = IconData(57599, fontFamily: 'Lucide');
  static const IconData leaf = IconData(58078, fontFamily: 'Lucide');
  static const IconData list = IconData(57606, fontFamily: 'Lucide');
  static const IconData lock = IconData(57611, fontFamily: 'Lucide');
  static const IconData logOut = IconData(57614, fontFamily: 'Lucide');
  static const IconData mapPin = IconData(57617, fontFamily: 'Lucide');
  static const IconData menu = IconData(57621, fontFamily: 'Lucide');
  static const IconData messageSquare = IconData(57623, fontFamily: 'Lucide');
  static const IconData mic = IconData(57624, fontFamily: 'Lucide');
  static const IconData micOff = IconData(57625, fontFamily: 'Lucide');
  static const IconData monitor = IconData(57629, fontFamily: 'Lucide');
  static const IconData moreVertical = IconData(57527, fontFamily: 'Lucide');
  static const IconData music = IconData(57634, fontFamily: 'Lucide');
  static const IconData play = IconData(57660, fontFamily: 'Lucide');
  static const IconData plus = IconData(57661, fontFamily: 'Lucide');
  static const IconData plusSquare = IconData(57715, fontFamily: 'Lucide');
  static const IconData power = IconData(57664, fontFamily: 'Lucide');
  static const IconData radar = IconData(58519, fontFamily: 'Lucide');
  static const IconData repeat = IconData(57670, fontFamily: 'Lucide');
  static const IconData rotateCcw = IconData(57672, fontFamily: 'Lucide');
  static const IconData rotateCw = IconData(57673, fontFamily: 'Lucide');
  static const IconData scanLine = IconData(57944, fontFamily: 'Lucide');
  static const IconData search = IconData(57681, fontFamily: 'Lucide');
  static const IconData send = IconData(57682, fontFamily: 'Lucide');
  static const IconData settings = IconData(57684, fontFamily: 'Lucide');
  static const IconData share2 = IconData(57686, fontFamily: 'Lucide');
  static const IconData shield = IconData(57688, fontFamily: 'Lucide');
  static const IconData shieldAlert = IconData(57854, fontFamily: 'Lucide');
  static const IconData shieldCheck = IconData(57855, fontFamily: 'Lucide');
  static const IconData shieldOff = IconData(57690, fontFamily: 'Lucide');
  static const IconData slash = IconData(58653, fontFamily: 'Lucide');
  static const IconData smartphone = IconData(57699, fontFamily: 'Lucide');
  static const IconData sparkles = IconData(58386, fontFamily: 'Lucide');
  static const IconData star = IconData(57718, fontFamily: 'Lucide');
  static const IconData sunMedium = IconData(58033, fontFamily: 'Lucide');
  static const IconData timer = IconData(57824, fontFamily: 'Lucide');
  static const IconData timerReset = IconData(57910, fontFamily: 'Lucide');
  static const IconData trash2 = IconData(57742, fontFamily: 'Lucide');
  static const IconData unlock = IconData(57612, fontFamily: 'Lucide');
  static const IconData x = IconData(57778, fontFamily: 'Lucide');
  static const IconData zap = IconData(57780, fontFamily: 'Lucide');
  static const IconData zapOff = IconData(57781, fontFamily: 'Lucide');
}

/// Type alias for Tx-branded design system icon references.
typedef TxIcons = LucideIcons;
